# Generated by Django 4.0.2 on 2022-05-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
