# Generated by Django 4.0.2 on 2022-08-04 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
