# Generated by Django 4.0.2 on 2022-08-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenceMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintence', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='pages',
            options={'verbose_name_plural': 'Pages'},
        ),
    ]
